apiVersion: v1
kind: Service
metadata:
  labels:
    app: metabase
  name: svc-metabase
spec:
  ports:
  - name: metabase
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: metabase2
  type: ClusterIP
